package-lock.json, src/components/Question.js, src/store/index.js
update store to convert data obj to array for questions
update Object.keys to Object.values
=> 18 update store

src/App.css, src/App.js, src/components/Home.js, src/components/Login.js, src/components/Navbar.js, src/components/SignUp.js, src/index.js, src/store/index.js
At the moment, logged in user does not persist if you close the browser.
=> 17-created navbar with signout/login && signout options

src/components/Level.js, src/components/MultipleChoice.js, src/components/Question.js, src/components/QuestionCreator.js, src/store/index.js
- added questions component so that we can load levels questions array, and iterate through them, so a user can progress through a path of questions
=> Questions flow

.babelrc, package-lock.json, package.json, src/App.js, src/configs/firebase_init.js, src/store/index.js, src/store/index.spec.js
- added 4 passing tests
- some updates to the state ({} => [], renamed 'user' to 'reducer', added .babelrc file to so files compile properly
=> 21 add test

src/App.css, src/components/ProgressBar/Filler.js, src/components/ProgressBar/ProgressBar.js, src/components/Question.js
added progress bar via progressbar and filler components
=> 20 create progress bar

src/components/InfoCard.js, src/components/MultipleChoice.js, src/components/Question.js, src/components/QuestionCreator.js
- added higher order component to create question components
- added functionality for true or false and info card components
=> Question creator component

src/components/Level.js, src/components/Results.js
simple results component with notes
=> 32 add results component

src/components/Question.js, src/components/Results.js
- added results page that renders when you complete level
- results page shows the number of questions you got right out of total questions
=> added dynamic results page

public/style.css, src/App.js, src/components/Home/Home.js, src/components/Home/SidePanel.js
- created a side panel on the home screen that will display current level and score, etc once that stuff is being stored in database and we can fetch!  : )
=> created side panel for homepage - needs to be hooked up to database

src/components/Home/Home.js, src/components/Home/SidePanel.js, src/components/Question.js
- fixed bug that was showing results page before you start the game (for like a nanosecond)
: )
=> 55 results page bug

src/components/ProgressBar/Filler.js, src/components/Question.js
- dried up code that renders progress bar
- made increment amount dynamic to each level
=> refactor: dried up code and refactored progress bar

package.json, src/components/Feedback.js, src/components/Login.js, src/components/ProgressBar/Filler.js, src/components/Question.js, src/components/Results.js, src/components/SignUp.js, src/store/index.js
=> Add user score

src/App.js, src/components/Leaderboard.js, src/components/Navbar.js, src/store/index.js
- In the redux store I updated the leaderboard so that usernames are added as players get added to the leaderboard. You'll now notice in our DB that leaderboard also includes username along with scores.
- then it was easier to fetch and render the leaderboard in the Leaderboard component.
=> live leaderboard renders top programmers - Rhianna is in the lead!!

src/App.js, src/components/Home/Home.js, src/components/Leaderboard.js, src/components/Login.js, src/components/Login.spec.js, src/components/Navbar.js, src/components/Navbar.spec.js, src/components/NoMatch.js, src/components/SignUp.js, src/store/index.js
- Navbar glitch was modified by updating Home component where it is now aware of 'isAuthorized' in state
- isAuthorized gets updated during login/logout
- Login.spec.js has new functioning test specs
- Navbar.spec.js has 1 passing & 1 skipped test. the reason for this is I'm struggling with figuring out how to get information from the store which effects what part of the component gets rendered. (ie. I want the signout button to be mounted BUT its only mounted when 'currentUser' is true).
=> Navbar-login-glitch

src/App.js, src/components/Leaderboard.js, src/components/Login.js, src/components/Navbar.js, src/components/Question.js, src/components/Results.js, src/components/SignUp.js, src/store/index.js, src/store/index.spec.js, src/store/reducers/currentLevelQuestions.js, src/store/reducers/currentUser.js, src/store/reducers/isAuthorized.js, src/store/reducers/leaderboard.js, src/store/reducers/userScore.js
- refactored the store/reducer so that each property of the store is its own file - easier to read and debug, should not be any change to functionality
=> 62 refactor the reducer

src/components/Navbar.js, src/components/Results.js
added a go home link on results page && removed leaderboard from navbar
=> added go home link to results removed leaderboard from navbar

public/style.css, src/components/Navbar.js
- changed nav bar so that the home link was removed, and now the codelingo logo text is a link to the home page instead
=> Remove home link

src/components/InfoCard.js, src/components/InfoFeedback.js, src/components/MultipleChoice.js
- infoCard can handle code snippets
=> Add level 3 questions from py

src/components/Results.js, src/store/reducers/userScore.js
- level up works again - remapped currentLevel to props
=> fix: level up works again

src/components/Home/Home.js, src/components/Question.js, src/components/Results.js, src/store/reducers/userScore.js
- to level up, checking if db-level and the level you just played are the same
=> Fix level up bug

public/index.html, public/nprogress.css, src/components/Question.js
- added nprogress bar for a subtle visual indicator that a page is loading
=> Nprogress for question fetch

package-lock.json, package.json
=> add nprogress package
